#!/usr/bin/env python3
import os
from argparse import ArgumentParser

import git


parser = ArgumentParser()
subparsers = parser.add_subparsers(dest="cmd")
subparsers.required = True

create_parser = subparsers.add_parser("create")
create_parser.add_argument("extension_name", help="extension name")
create_parser.add_argument("url", help="extension name")

install_parser = subparsers.add_parser("install")
install_parser.add_argument("extensions", nargs="+", help="extensions to install")

update_parser = subparsers.add_parser("update")
update_parser.add_argument("extensions", nargs="+", help="extensions to update")

remove_parser = subparsers.add_parser("remove")
remove_parser.add_argument("extensions", nargs="+", help="extensions to remove")

list_parser = subparsers.add_parser("list")

args = parser.parse_args()


if __name__ == "__main__":
    # Move to root directory of project
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    install_path = os.path.join("include", "BaseGraph", "extensions")

    basegraph_repo = git.Repo(".")

    if args.cmd == "install":
        for submodule in basegraph_repo.submodules:
            if submodule.name in args.extensions:
                if submodule.exists():
                    print(f"Extension \"{submodule.name}\" is already installed. "
                           "Use the \"update\" command to update it.")
                    continue
                submodule.update(init=True)

    elif args.cmd == "create":
        for submodule in basegraph_repo.submodules:
            if submodule.name == args.extension_name:
                print(f"Cannot create extension \"{args.extension_name}\": "
                       "the extension already exists/the name is already used.")
        basegraph_repo.create_submodule(
            path = os.path.join(install_path, args.extension_name),
            url = args.url,
            name = args.extension_name
        )
        print(f"Created extension \"{args.extension_name}\".")

    elif args.cmd == "list":
        print("Installed extensions:")
        for submodule in basegraph_repo.submodules:
            if submodule.exists():
                commit = submodule.hexsha
                print(f"{submodule.name:<17}commit {str(commit)[:8]}")

    elif args.cmd == "update":
        for submodule in basegraph_repo.submodules:
            if submodule.name in args.extensions:
                if not submodule.exists():
                    print(f"Extension \"{submodule.name}\" is not installed. "
                           "Use the \"install\" command to install it.")
                    continue
                submodule.update()

    elif args.cmd == "remove":
        for submodule in basegraph_repo.submodules:
            if submodule.name in args.extensions and submodule.exists():
                submodule.remove()
