macro(SUBDIRLIST result curdir)
  file(GLOB children RELATIVE ${curdir} ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()


macro(add_gtest _testname)
    list(APPEND allGTests ${_testname})
    set(allGTests ${allGTests} PARENT_SCOPE)
endmacro()

macro(add_extension _extension)
    set_target_properties(${_extension} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
    list(APPEND BaseGraphExtensions ${_extension})
    set(BaseGraphExtensions ${BaseGraphExtensions} PARENT_SCOPE)
endmacro()
