name: Wrapper tests

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_wrapper:
    name: Test Python wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install BaseGraph and dependencies
        run:
          pip install --upgrade pip
          pip install -r test_requirements.txt
          pip install pybind11
          pip install .

      - name: Test
        shell: bash
        run: pytest
