name: C++ unit tests

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_core:
    name: Test C++ core
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure BaseGraph CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build BaseGraph
      run: cmake --build ${{github.workspace}}/build

    - name: CMake install
      run: cmake --install build --prefix "${{github.workspace}}/local_install"

    - name: Unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose

    - name: Configure example
      run: cmake -B ${{github.workspace}}/examples/build -DCMAKE_PREFIX_PATH="${{github.workspace}}/local_install"

    - name: Build example
      run: cmake --build ${{github.workspace}}/examples/build
