name: Python build

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_wrapper:
    name: Test Python module building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install BaseGraph
        run:
          pip install .

      - name: Import BaseGraph core
        run:
          python -c "import basegraph; basegraph.core; from basegraph import core"
