name: Python build

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_wrapper:
    name: Test Python module building
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11", "pypy-3.8"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install BaseGraph
        run:
          pip install .[test]

      - name: Import BaseGraph core
        run:
          python -c "import basegraph"
          python -c "import basegraph.core"
          python -c "from basegraph import core"
