name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
      
  test_wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
          cache: pip

      - name: Test Python wrapper
        shell: bash
        run: pip install --upgrade pip
             pip install pybind11 pytest
             pip install .
             pytest
