name: Run tests

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_core:
    name: Test C++ core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

  test_wrapper:
    name: Test Python wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install BaseGraph and dependencies
        run:
          pip install --upgrade pip
          pip install -r test_requirements.txt
          pip install pybind11
          pip install .

      - name: Test
        shell: bash
        run: pytest
